# Generated by Django 4.1.2 on 2023-12-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('format', '0002_authorityletter_statusvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityletter',
            name='executiveName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
