# Generated by Django 4.1.2 on 2023-12-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('format', '0004_depositofpayment_executivename'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositofpayment',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
