# Generated by Django 4.1.2 on 2022-11-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrarOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
