# Generated by Django 4.1.2 on 2022-11-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registraroffice',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
