# Generated by Django 4.1.2 on 2022-11-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0002_alter_registraroffice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='handledBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
