# Generated by Django 4.1.2 on 2022-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0003_handledby'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='delTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='differentRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
