# Generated by Django 4.1.2 on 2022-11-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0004_bank_branch_deltable_differentremarks_dsa_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='contactperson',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='fax',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='phoneOne',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='phonetwo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='std',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
