# Generated by Django 4.1.2 on 2022-11-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0006_rename_contactperson_bank_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsa',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dsa',
            name='delValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dsa',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
