# Generated by Django 4.1.2 on 2022-11-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0007_dsa_address_dsa_delvalue_dsa_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
