# Generated by Django 4.1.2 on 2022-11-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0008_branch_address_branch_bank_branch_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='bankName',
        ),
    ]
