# Generated by Django 4.1.2 on 2022-11-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalMaster', '0009_rename_bank_branch_bankname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='FeeinRs',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='particulars',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
