# Generated by Django 4.1.2 on 2022-11-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disbursalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=250, null=True)),
                ('branchName', models.CharField(blank=True, max_length=250, null=True)),
                ('registrationDate', models.CharField(blank=True, max_length=250, null=True)),
                ('transNo', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('dsa', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('seller', models.CharField(blank=True, max_length=250, null=True)),
                ('registrarOff', models.CharField(blank=True, max_length=250, null=True)),
                ('purchaser', models.CharField(blank=True, max_length=250, null=True)),
                ('reciptNo', models.CharField(blank=True, max_length=250, null=True)),
                ('rdSentOn', models.CharField(blank=True, max_length=250, null=True)),
                ('sdSentOn', models.CharField(blank=True, max_length=250, null=True)),
                ('tdSentOn', models.CharField(blank=True, max_length=250, null=True)),
                ('sentAt', models.CharField(blank=True, max_length=250, null=True)),
                ('caseClosed', models.CharField(blank=True, max_length=250, null=True)),
                ('courierDate', models.CharField(blank=True, max_length=250, null=True)),
                ('propertyDetails', models.CharField(blank=True, max_length=250, null=True)),
                ('deedWriterAdv', models.CharField(blank=True, max_length=250, null=True)),
                ('handledBy', models.CharField(blank=True, max_length=250, null=True)),
                ('applicationNo', models.CharField(blank=True, max_length=250, null=True)),
                ('pageNo', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('otherRemarkIfAny', models.CharField(blank=True, max_length=250, null=True)),
                ('checqueDate', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('chequeRecivedDate', models.CharField(blank=True, max_length=250, null=True)),
                ('chequeReturnDate', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
