# Generated by Django 4.0.3 on 2023-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursal', '0002_disbursalbt'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursalbt',
            name='uid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalregistration',
            name='uid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
