# Generated by Django 4.0 on 2023-06-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursal', '0004_disbursalregistration_ackrecived'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursalbt',
            name='ackRecived',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
