# Generated by Django 4.0 on 2023-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursal', '0006_disbursalbt_nextdate_disbursalregistration_nextdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursalbt',
            name='ack',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalbt',
            name='slNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalbt',
            name='volNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalregistration',
            name='ack',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalregistration',
            name='slNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalregistration',
            name='volNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
