# Generated by Django 4.1.2 on 2023-07-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursal', '0007_disbursalbt_ack_disbursalbt_slno_disbursalbt_volno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursalbt',
            name='statusValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='disbursalregistration',
            name='statusValue',
            field=models.CharField(default='true', max_length=250),
        ),
    ]
