# Generated by Django 3.2.16 on 2024-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursal', '0011_disbursalbt_casecloseval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disbursalbt',
            old_name='date',
            new_name='registrationDate',
        ),
    ]
