# Generated by Django 4.1.2 on 2022-11-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='optionPrepareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciptDate', models.DateField(blank=True, null=True)),
                ('bankRefNo', models.CharField(max_length=250)),
                ('bank', models.CharField(blank=True, max_length=250, null=True)),
                ('branch', models.CharField(blank=True, max_length=250, null=True)),
                ('apsNo', models.CharField(max_length=250)),
                ('report', models.CharField(blank=True, max_length=250, null=True)),
                ('customerBorrower', models.CharField(blank=True, max_length=250, null=True)),
                ('repNo', models.CharField(max_length=250)),
                ('profCharges', models.CharField(max_length=250)),
                ('inspectionReceipt', models.CharField(max_length=250)),
                ('outOfPocketExp', models.CharField(max_length=250)),
                ('flatHousePlotNo', models.CharField(max_length=250)),
                ('roofRight', models.CharField(max_length=250)),
                ('floor', models.CharField(max_length=250)),
                ('RepRefNo', models.CharField(max_length=250)),
                ('streetSectorLocal', models.CharField(max_length=250)),
                ('referBy', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('reportDate', models.DateField(blank=True, null=True)),
                ('phoneNo', models.CharField(max_length=250)),
                ('reportSentThru', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('reportSentOn', models.CharField(max_length=250)),
                ('receivedBy', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('collectedBy', models.CharField(max_length=250)),
                ('preparedBy', models.CharField(max_length=250)),
                ('nature', models.CharField(max_length=250)),
                ('statusValue', models.CharField(max_length=250)),
                ('remarks', models.TextField()),
                ('fallowUp', models.TextField()),
                ('fileUpload', models.CharField(max_length=250)),
                ('status', models.CharField(default='true', max_length=250)),
            ],
        ),
    ]
