# Generated by Django 4.1.2 on 2022-11-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reciptDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reportDate',
            field=models.CharField(max_length=250),
        ),
    ]
