# Generated by Django 4.1.2 on 2022-11-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0002_alter_optionpreparereport_reciptdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionpreparereport',
            name='RepRefNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='apsNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='bankRefNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='collectedBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='fallowUp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='flatHousePlotNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='floor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='inspectionReceipt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='nature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='outOfPocketExp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='preparedBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='profCharges',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='receivedBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reciptDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='referBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='repNo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reportDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reportSentOn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='reportSentThru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='roofRight',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='statusValue',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='optionpreparereport',
            name='streetSectorLocal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
