# Generated by Django 4.1.2 on 2022-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0003_alter_optionpreparereport_reprefno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpreparereport',
            name='searchExp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
