# Generated by Django 4.1.2 on 2023-07-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_optionpreparereport_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionpreparereport',
            name='netFallowUpDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
