# Generated by Django 4.1.2 on 2022-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='builderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciptDate', models.DateTimeField(blank=True, null=True)),
                ('fileNo', models.CharField(max_length=250)),
                ('bank', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('loanACNo', models.CharField(max_length=250)),
                ('collectedBy', models.IntegerField(blank=True, null=True)),
                ('handledByName', models.IntegerField(blank=True, null=True)),
                ('refNo', models.CharField(max_length=250)),
                ('customerBorrower', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('std', models.CharField(max_length=250)),
                ('dated', models.DateTimeField(blank=True, null=True)),
                ('forRs', models.CharField(max_length=250)),
                ('favoring', models.TextField()),
                ('reciptNo', models.CharField(max_length=250)),
                ('amount', models.FloatField(default=0.0)),
                ('recDate', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
