# Generated by Django 4.1.2 on 2022-10-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builderPayment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builderpayment',
            old_name='std',
            new_name='payOrderNo',
        ),
    ]
