# Generated by Django 4.1.2 on 2022-10-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builderPayment', '0002_rename_std_builderpayment_payorderno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderpayment',
            name='dated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builderpayment',
            name='recDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builderpayment',
            name='reciptDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
