# Generated by Django 4.1.2 on 2022-10-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builderPayment', '0003_alter_builderpayment_dated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderpayment',
            name='bank',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='builderpayment',
            name='branch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='builderpayment',
            name='collectedBy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='builderpayment',
            name='handledByName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
